name: Expo App Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm install

      - name: Log in to Expo
        env:
          EXPO_CLI_USERNAME: ${{ secrets.EXPO_CLI_USERNAME }}
          EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
        run: |
          expo login --non-interactive -u $EXPO_CLI_USERNAME
          expo whoami # for verification

      - name: Creating build using EAS
        run: npx eas build -p android

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: expo-build
          path: ./app-release.apk
